/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gamethread;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author risulkarim
 */
public class GameThreadView extends javax.swing.JFrame {

    /**
     * Creates new form GameThreadView
     */
    public GameThreadView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dRight = new javax.swing.JButton();
        dLeft = new javax.swing.JButton();
        mLeft = new javax.swing.JButton();
        mRight = new javax.swing.JButton();
        mCar = new javax.swing.JButton();
        dMiddle = new javax.swing.JButton();
        start = new javax.swing.JButton();
        timer = new javax.swing.JTextField();
        gameStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dRight.setText("Decepticon R");
        dRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRightActionPerformed(evt);
            }
        });
        getContentPane().add(dRight);
        dRight.setBounds(313, 0, 90, 23);

        dLeft.setText("Decepticon L");
        dLeft.setPreferredSize(new java.awt.Dimension(20, 20));
        dLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLeftActionPerformed(evt);
            }
        });
        getContentPane().add(dLeft);
        dLeft.setBounds(0, 0, 90, 20);

        mLeft.setText("<");
        mLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLeftActionPerformed(evt);
            }
        });
        getContentPane().add(mLeft);
        mLeft.setBounds(140, 270, 41, 23);

        mRight.setText(">");
        mRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRightActionPerformed(evt);
            }
        });
        getContentPane().add(mRight);
        mRight.setBounds(180, 270, 41, 23);

        mCar.setText("My Car");
        mCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCarActionPerformed(evt);
            }
        });
        getContentPane().add(mCar);
        mCar.setBounds(150, 240, 67, 23);

        dMiddle.setText("Decepticon M");
        getContentPane().add(dMiddle);
        dMiddle.setBounds(150, 0, 97, 23);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(280, 310, 57, 23);

        timer.setText("jTextField1");
        getContentPane().add(timer);
        timer.setBounds(0, 300, 220, 30);

        gameStatus.setText("Cars beaten: ");
        getContentPane().add(gameStatus);
        gameStatus.setBounds(500, 300, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRightActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dRightActionPerformed

    private void dLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLeftActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_dLeftActionPerformed
    
    private void mLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLeftActionPerformed
            // TODO add your handling code here:
        
        mCar.setBounds(mCar.getX()-20, mCar.getY(), mCar.getWidth(), mCar.getHeight());
        mCarX=mCar.getX();
        mCarY=mCar.getY();
        mCarWidth=mCar.getWidth();
        mCarHeight=mCar.getHeight();
    }//GEN-LAST:event_mLeftActionPerformed

    private void mRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRightActionPerformed
        // TODO add your handling code here:
        
        mCar.setBounds(mCar.getX()+20, mCar.getY(), mCar.getWidth(), mCar.getHeight());
        mCarX=mCar.getX();
        mCarY=mCar.getY();
        mCarWidth=mCar.getWidth();
        mCarHeight=mCar.getHeight();
    }//GEN-LAST:event_mRightActionPerformed

    private void mCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCarActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here: GameObject gameObject = new GameObject(dLeft);
       GameObject gameObject = new GameObject(dLeft);
       Thread gOThread = new Thread(gameObject, "leftCar");
       gOThread.start();
        gameObject = new GameObject(dMiddle);
       Thread gOThread2 = new Thread(gameObject,"middleCar");
       gOThread2.start();
        gameObject = new GameObject(dRight);
       Thread gOThread3 = new Thread(gameObject,"rightCar");
       gOThread3.start();
       
       new Thread(){
           int time=0;
         public void run(){
             for (int i = 0; i <=120; i++) {
             
             if(GameObject.game){
                 timer.setText("Time Elapsed: "+time++);
             gameStatus.setText("Cars beaten: "+carsBeaten);
             }
            
                 else
                 gameStatus.setText("GameOver");
               try {
                   sleep(1000);
               } catch (InterruptedException ex) {
                   Logger.getLogger(GameThreadView.class.getName()).log(Level.SEVERE, null, ex);
               }
             }
             GameObject.game=false;
             gameStatus.setText("Cars beaten: "+carsBeaten+" Conrats You Won");
         }  
       }.start();
    }//GEN-LAST:event_startActionPerformed
    static int carsBeaten=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameThreadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameThreadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameThreadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameThreadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameThreadView().setVisible(true);
            }
        });
    }
    static int mCarX;
    static int mCarY;
    static int mCarWidth;
    static int mCarHeight;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dLeft;
    private javax.swing.JButton dMiddle;
    private javax.swing.JButton dRight;
    private javax.swing.JTextField gameStatus;
    private javax.swing.JButton mCar;
    private javax.swing.JButton mLeft;
    private javax.swing.JButton mRight;
    private javax.swing.JButton start;
    private javax.swing.JTextField timer;
    // End of variables declaration//GEN-END:variables
    
    
}
